name: Build and upload

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRING_HEX: ${{ secrets.SECRING_HEX }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Create secring.gpg
      run: echo $SECRING_HEX > secring.gpg.hex && xxd -p -r secring.gpg.hex > secring.gpg
    - name: Configure Gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --no-daemon --no-parallel --rerun-tasks --info --full-stacktrace build
    - name: Upload archives
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: ./gradlew --no-daemon --no-parallel --info -Psigning.secretKeyRingFile=$PWD/secring.gpg -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -PnexusUsername=$NEXUS_USER -PnexusPassword=$NEXUS_PASSWORD -Poss-releases.username=$NEXUS_USER -Poss-releases.password=$NEXUS_PASSWORD --full-stacktrace uploadArchives
    - name: Sleep for 30 seconds
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Nexus staging release
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: ./gradlew --no-daemon --no-parallel --info -Psigning.secretKeyRingFile=$PWD/secring.gpg -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -PnexusUsername=$NEXUS_USER -PnexusPassword=$NEXUS_PASSWORD -Poss-releases.username=$NEXUS_USER -Poss-releases.password=$NEXUS_PASSWORD --full-stacktrace nexusStagingRelease
